steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --target production \
          --build-arg DEBUG="$_DEBUG" \
          -t $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        if gcloud run jobs describe "$_MIGRATE_JOB_NAME" --region "$_DEPLOY_REGION" >/dev/null 2>&1; then
          echo "Job exists. Updating..."
          gcloud run jobs update "$_MIGRATE_JOB_NAME" \
            --image "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA" \
            --region "$_DEPLOY_REGION" \
            --service-account "ci-cd-service-account@ci-cd-project-490723.iam.gserviceaccount.com" \
            --set-cloudsql-instances "ci-cd-project-490723:southamerica-west1:ci-cd-postgres" \
            --set-env-vars "DEBUG=$_DEBUG" \
            --set-secrets "DJANGO_SECRET_KEY=DJANGO_SECRET_KEY:latest" \
            --command python \
            --args manage.py,migrate,--noinput
        else
          echo "Job does not exist. Creating..."
          gcloud run jobs create "$_MIGRATE_JOB_NAME" \
            --image "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA" \
            --region "$_DEPLOY_REGION" \
            --add-cloudsql-instances "ci-cd-project-490723:southamerica-west1:ci-cd-postgres" \
            --service-account "ci-cd-service-account@ci-cd-project-490723.iam.gserviceaccount.com" \
            --set-cloudsql-instances "ci-cd-project-490723:southamerica-west1:ci-cd-postgres" \
            --set-env-vars "DEBUG=$_DEBUG" \
            --set-secrets "DJANGO_SECRET_KEY=DJANGO_SECRET_KEY:latest" \
            --command python \
            --args manage.py,migrate,--noinput
        fi
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
      - '--service-account'
      - ci-cd-service-account@ci-cd-project-490723.iam.gserviceaccount.com
      - '--allow-unauthenticated'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
      - '--add-cloudsql-instances'
      - 'ci-cd-project-490723:southamerica-west1:ci-cd-postgres'
      - '--update-env-vars'
      - 'DEBUG=$_DEBUG'
      - '--update-secrets'
      - 'DJANGO_SECRET_KEY=DJANGO_SECRET_KEY:latest'
    entrypoint: gcloud
timeout: 1200s
images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY