# Generated by Django 6.0.3 on 2026-04-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_document',
            field=models.ImageField(null=True, storage={'BACKEND': 'django.core.files.storage.FileSystemStorage'}, upload_to='identity/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, storage={'BACKEND': 'django.core.files.storage.FileSystemStorage'}, upload_to='profiles/'),
        ),
    ]
