# Generated by Django 6.0.3 on 2026-04-03 01:53

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_identity_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identity_document',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/private/', location=pathlib.PurePosixPath('/Users/maximilianoopitzturra/Documents/Programming/ci-cd-test/ci-cd-tutorial/media/private')), upload_to='identity/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/public/', location=pathlib.PurePosixPath('/Users/maximilianoopitzturra/Documents/Programming/ci-cd-test/ci-cd-tutorial/media/public')), upload_to='profiles/'),
        ),
    ]
